export const products = [
  {
    name: "Novabell",
    category: "Pavimenti e Rivestimenti",
    url: "https://www.novabell.it",
    img: "/loghi/logo-1.jpg",
  },
  {
    name: "Dado",
    category: "Pavimenti e Rivestimenti",
    url: "https://www.dadoceramica.it",
    img: "/loghi/logo-2.png",
  },
  {
    name: "Impronta",
    category: "Pavimenti e Rivestimenti",
    url: "https://www.italgranitigroup.com/it/collezioni/impronta",
    img: "/loghi/logo-3.svg",
  },
  {
    name: "Antica Ceramica di Rubiera",
    category: "Pavimenti e Rivestimenti",
    url: "https://www.anticaceramica.it/",
    img: "/loghi/logo-4.png",
  },
  {
    name: "Prismacer",
    category: "Pavimenti e Rivestimenti",
    url: "https://www.prissmacer.es/",
    img: "/loghi/logo-5.svg",
  },
  {
    name: "Studio One",
    category: "Pavimenti e Rivestimenti",
    url: "https://www.studioonesrl.it/",
    img: "/loghi/logo-6.jpg",
  },
  {
    name: "Exagres",
    category: "Pavimenti e Rivestimenti",
    url: "https://www.exagres.es",
    img: "/loghi/logo-7.png",
  },
  {
    name: "Flaviker",
    category: "Pavimenti e Rivestimenti",
    url: "https://www.flavikerpisa.it",
    img: "/loghi/logo-8.svg",
  },
  {
    name: "Tecnolam",
    category: "Pavimenti e Rivestimenti",
    url: "https://www.tecnolam.it",
    img: "/loghi/logo-9.png",
  },
  {
    name: "Mac3",
    category: "Pavimenti e Rivestimenti",
    url: "https://mac3.it/",
    img: "/loghi/logo-10.png",
  },
  {
    name: "Keradom",
    category: "Pavimenti e Rivestimenti",
    url: "https://www.keradom.it",
    img: "/loghi/logo-11.png",
  },
  {
    name: "Cerasarda",
    category: "Pavimenti e Rivestimenti",
    url: "https://www.cerasarda.it",
    img: "/loghi/logo-12.webp",
  },
  {
    name: "Tavar",
    category: "Parquet",
    url: "https://www.tavar.it",
    img: "/loghi/logo-13.png",
  },
  {
    name: "Parquet Italia",
    category: "Parquet",
    url: "https://www.parquetitalia1960.it/",
    img: "/loghi/logo-14.png",
  },
  {
    name: "Azzurra",
    category: "Sanitari",
    url: "https://www.azzurraceramica.it",
    img: "/loghi/logo-15.svg",
  },
  {
    name: "Globo",
    category: "Sanitari",
    url: "https://www.ceramicaglobo.com",
    img: "/loghi/logo-16.svg",
  },
  {
    name: "Nic",
    category: "Sanitari",
    url: "https://www.nicdesign.it",
    img: "/loghi/logo-17.png",
  },
  {
    name: "Disegno Ceramica",
    category: "Sanitari",
    url: "https://www.disegnoceramica.com",
    img: "/loghi/logo-18.png",
  },
  {
    name: "Archeda",
    category: "Arredo bagno",
    url: "https://www.archeda.eu/",
    img: "/loghi/logo-19.png",
  },
  {
    name: "Arcom",
    category: "Arredo bagno",
    url: "https://www.arcom.it",
    img: "/loghi/logo-20.webp",
  },
  {
    name: "Falegnameria Adriatica",
    category: "Arredo bagno",
    url: "https://www.faonline.it/",
    img: "/loghi/logo-21.png",
  },
  {
    name: "Nic",
    category: "Arredo bagno",
    url: "https://www.nicdesign.it",
    img: "/loghi/logo-17.png",
  },
  {
    name: "Arblu'",
    category: "Arredo bagno",
    url: "https://www.arblu.it",
    img: "/loghi/logo-22.png",
  },
  {
    name: "Treemme",
    category: "Rubinetteria",
    url: "https://www.rubinetterie3m.it/it",
    img: "/loghi/logo-23.png",
  },
  {
    name: "Vema",
    category: "Rubinetteria",
    url: "https://vemarubinetterie.it/",
    img: "/loghi/logo-24.png",
  },
  {
    name: "Demm",
    category: "Rubinetteria",
    url: "https://www.demmrubinetteria.it/",
    img: "/loghi/logo-25.png",
  },
  {
    name: "PDP",
    category: "Box doccia",
    url: "https://www.pdpboxdoccia.com",
    img: "/loghi/logo-26.png",
  },
  {
    name: "Arblu'",
    category: "Box doccia",
    url: "https://www.arblu.it",
    img: "/loghi/logo-22.png",
  },
  {
    name: "GME",
    category: "Box doccia",
    url: "https://gmelorente.com/it/",
    img: "/loghi/logo-27.png",
  },
  {
    name: "Relax",
    category: "Box doccia",
    url: "https://relaxsrl.com/",
    img: "/loghi/logo-28.jpg",
  },
];
