export const products = [
  {
    title: "Novabell",
    category: "Pavimenti e Rivestimenti",
    url: "https://www.novabell.it",
    image: "/loghi/logo-1.png",
  },
  {
    title: "Dado",
    category: "Pavimenti e Rivestimenti",
    url: "https://www.dadoceramica.it",
    image: "/loghi/logo-2.png",
  },
  {
    title: "Impronta",
    category: "Pavimenti e Rivestimenti",
    url: "https://www.italgranitigroup.com/it/collezioni/impronta",
    image: "/loghi/logo-3.svg",
  },
  {
    title: "Antica Ceramica di Rubiera",
    category: "Pavimenti e Rivestimenti",
    url: "https://www.anticaceramica.it/",
    image: "/loghi/logo-4.png",
  },
  {
    title: "Prismacer",
    category: "Pavimenti e Rivestimenti",
    url: "https://www.prissmacer.es/",
    image: "/loghi/logo-5.svg",
  },
  {
    title: "Studio One",
    category: "Pavimenti e Rivestimenti",
    url: "https://www.studioonesrl.it/",
    image: "/loghi/logo-6.jpg",
  },
  {
    title: "Exagres",
    category: "Pavimenti e Rivestimenti",
    url: "https://www.exagres.es",
    image: "/loghi/logo-7.png",
  },
  {
    title: "Flaviker",
    category: "Pavimenti e Rivestimenti",
    url: "https://www.flavikerpisa.it",
    image: "/loghi/logo-8.svg",
  },
  {
    title: "Technolam",
    category: "Pavimenti e Rivestimenti",
    url: "https://technolam.it/",
    image: "/loghi/logo-9.png",
  },
  {
    title: "Mac3",
    category: "Pavimenti e Rivestimenti",
    url: "https://mac3.it/",
    image: "/loghi/logo-10.png",
  },
  {
    title: "Keradom",
    category: "Pavimenti e Rivestimenti",
    url: "https://www.keradom.it/brands/mac3/",
    image: "/loghi/logo-11.png",
  },
  {
    title: "Cerasarda",
    category: "Pavimenti e Rivestimenti",
    url: "https://www.cerasarda.it",
    image: "/loghi/logo-12.webp",
  },
  {
    title: "Tavar",
    category: "Parquet",
    url: "https://www.tavar.it",
    image: "/loghi/logo-13.png",
  },
  {
    title: "Parquet Italia",
    category: "Parquet",
    url: "https://www.parquetitalia1960.it/",
    image: "/loghi/logo-14.png",
  },
  {
    title: "Azzurra",
    category: "Sanitari",
    url: "https://www.azzurraceramica.it",
    image: "/loghi/logo-15.svg",
  },
  {
    title: "Globo",
    category: "Sanitari",
    url: "https://www.ceramicaglobo.com",
    image: "/loghi/logo-16.svg",
  },
  {
    title: "Nic",
    category: "Sanitari",
    url: "https://www.nicdesign.it",
    image: "/loghi/logo-17.png",
  },
  {
    title: "Disegno Ceramica",
    category: "Sanitari",
    url: "https://www.disegnoceramica.com",
    image: "/loghi/logo-18.png",
  },
  {
    title: "Archeda",
    category: "Arredo bagno",
    url: "https://www.archeda.eu/",
    image: "/loghi/logo-19.png",
  },
  {
    title: "Arcom",
    category: "Arredo bagno",
    url: "https://www.arcombagno.com/",
    image: "/loghi/logo-20.webp",
  },
  {
    title: "Falegnameria Adriatica",
    category: "Arredo bagno",
    url: "https://www.faonline.it/",
    image: "/loghi/logo-21.png",
  },
  {
    title: "Nic",
    category: "Arredo bagno",
    url: "https://www.nicdesign.it",
    image: "/loghi/logo-17.png",
  },
  {
    title: "Arblu'",
    category: "Arredo bagno",
    url: "https://www.arblu.it",
    image: "/loghi/logo-22.png",
  },
  {
    title: "Treemme",
    category: "Rubinetteria",
    url: "https://www.rubinetterie3m.it/it",
    image: "/loghi/logo-23.png",
  },
  {
    title: "Vema",
    category: "Rubinetteria",
    url: "https://vemarubinetterie.it/",
    image: "/loghi/logo-24.png",
  },
  {
    title: "Demm",
    category: "Rubinetteria",
    url: "https://www.demmrubinetteria.it/",
    image: "/loghi/logo-25.png",
  },
  {
    title: "PDP",
    category: "Box doccia",
    url: "https://www.pdpboxdoccia.com",
    image: "/loghi/logo-26.png",
  },
  {
    title: "Arblu'",
    category: "Box doccia",
    url: "https://www.arblu.it",
    image: "/loghi/logo-22.png",
  },
  {
    title: "GME",
    category: "Box doccia",
    url: "https://gmelorente.com/it/",
    image: "/loghi/logo-27.png",
  },
  {
    title: "Relax",
    category: "Box doccia",
    url: "https://relaxsrl.com/",
    image: "/loghi/logo-28.png",
  },
  {
    title: "IRSAP",
    category: "Arredo bagno",
    url: "https://www.irsap.com/it",
    image: "/loghi/logo-29.svg",
  },
  {
    title: "Caleido",
    category: "Arredo bagno",
    url: "https://www.caleido.it/",
    image: "/loghi/logo-32.svg",
  },
  {
    title: "Londonart",
    category: "Finiture D'Arredo",
    url: "https://www.londonart.it/it/home",
    image: "/loghi/logo-30.png",
  },
  {
    title: "Venus",
    category: "Finiture D'Arredo",
    url: "https://www.venusdesign.eu/",
    image: "/loghi/logo-31.svg",
  },
];
